wiki_title_suffix: " - Wiki"

pages:
  EnttAPI:
    title: "EnttAPI"
    subtitle: "Developer API"
    description: "EnttAPI is an API under development created by me (EnttbotX) to simplify and speed up plugin development. It includes many features and plans for implementing them."
    icon: "https://www.spigotmc.org/data/resource_icons/127/127845.jpg?1754810224"
    buttons:
      - text: "GitHub Repo"
        url: "https://github.com/enttbotx"
        class: "btn-primary"
      - text: "Spigot Page"
        url: "https://www.spigotmc.org/resources/enttapi-official-enttbot-api-1-8-1-21.127845/"
        class: "btn-primary"
    
    modules:
      - id: "mysql"
        title: "Módulo MySQL"
        short_desc: "Elimina la necesidad de configurar SQL manual."
        content: "Este módulo te permite conectar bases de datos de forma automática. Olvídate de escribir queries repetitivos, EnttAPI gestiona los pools de conexiones por ti."
      
      - id: "peron"
        title: "Módulo Peron"
        short_desc: "Gestión de lógicas internas personalizadas."
        content: "Descripción detallada sobre el funcionamiento del módulo Peron y sus implementaciones principales en el entorno de desarrollo."
      
      - id: "loc"
        title: "Módulo Loc"
        short_desc: "Manejador de localizaciones y vectores avanzados."
        content: "Simplifica el guardado y carga de localizaciones en archivos de configuración, manteniendo la compatibilidad entre distintas versiones de Spigot/Paper."
      
      - id: "pepe"
        title: "Módulo Pepe"
        short_desc: "Utilerías del sistema secundario."
        content: "Contenido específico del módulo Pepe, con ejemplos prácticos sobre cómo registrar eventos de manera dinámica."
